### ISSUE TITLE
Problems with non ASCII characters

### ISSUE THREAD

**Issue by jorgonzalez** [endocode/timy#5]
If projects or comments contain non ASCII characters, timy might crash because of the encoding. 

The following crash is a fresh installation with python3. The project where it crashes contains "ö". Using ubuntu:16.04.

```
root@74bc31579ab5:/# virtualenv -p python3 timy.env
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /timy.env/bin/python3
Also creating executable in /timy.env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
root@74bc31579ab5:/# /timy.env/bin/pip3 install git+https://github.com/endocode/timy.git
[...]
root@74bc31579ab5:/# timy.env/bin/timy list projects
#Project ID	-	Project Name
================================================================================
#1		-	bla
Traceback (most recent call last):
  File "timy.env/bin/timy", line 10, in <module>
    sys.exit(main())
  File "/timy.env/lib/python3.5/site-packages/timy/track_charm.py", line 336, in main
    ctt.processing_func()
  File "/timy.env/lib/python3.5/site-packages/timy/track_charm.py", line 271, in print_all_projects
    print("#{}\t\t-\t{}".format(project.id, project.name))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 12: ordinal not in range(128)
```

Files affected:
`track_charm.py `
Functions
```
    def print_all_projects(self):
        print("#Project ID\t-\tProject Name".format())
        print("="*80)
        for project in self.redmine.project.all():
            print("#{}\t\t-\t{}".format(project.id, project.name))
```
And
```
    def print_time_tracks_from(self):
        summarized_hours = 0

        current_user = self.redmine.user.get(self.user)
        print("Time tracks for user {} {}".format(current_user.firstname, current_user.lastname))
        time_entries = self.redmine.time_entry.all(user_id=current_user.id, sort="spent_on", from_date=self.start_from_date, to_date=self.end_at_date)

        try:
            self.current_day = time_entries[0].spent_on
        except ResourceSetIndexError:
            print("Unable to retrive time tracks from {} to {}".format(self.start_from_date, self.end_at_date))
            return

        self.day_hours = 0.0

        for te in time_entries:
            if self.verbose and self.sumday and te.spent_on > self.current_day:
                self.print_daily_totals()
                self.next_day(te.spent_on)

            summarized_hours += te.hours
            if self.sumday:
                self.day_hours += te.hours
            if self.verbose:
                if not "comments" in dir(te):
                    te.comments = ""
                print("{} spent {} {} hours on {} - {}".format(te.spent_on, te.hours, te.activity, te.project, te.comments.))

```

**Comment by hemarkus** [comment]
`export PYTHONIOENCODING=utf-8` should solve it.
